# Generated by Django 4.2.6 on 2023-10-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=191)),
            ],
        ),
    ]
